### ISSUE TITLE
Simplex is Patented

### ISSUE THREAD

**Issue by zauberparacelsus** [OvermindDL1/Godot-Helpers#1]
I'm sorry to report this as it probably kills off most of your project, but implementations of Simplex noise that output 3d noise or higher are patented and cannot be used without licensing, unless you want to wait for the patent to expire in 2022 :-/

The 2D implementation is safe to use, however.

Though, perhaps as a "fix" you can check into the OpenSimplex algorithm?  It is not affected by the patent on simplex.  The noise it outputs is different from Simplex and it may be slightly slower, though it's still much faster than perlin noise.

**Comment by OvermindDL1** [comment]
Even if this is based on the 2d but abstracted out to any dimension?  That seems odd and illogical, it is a mathematical function...

**Comment by zauberparacelsus** [comment]
Well, if your 3D/4D/etc implementations are different, and if they produce different results than the official implementations when using the same inputs, then it probably isn't infringing.

**Comment by OvermindDL1** [comment]
That is a great question, I am not actually sure if the 3d variant is different from a dimensionally abstracted 2d variant, I had never tested...  I should do that someday, unless someone beats me to it?  (hint hint)

**Comment by OvermindDL1** [comment]
Furthermore, if they do give the same results than how could one be patented when the other is just a more generic variant of the unpatented version?

**Comment by OvermindDL1** [comment]
No comments in a long time and no comparisons given, thus closing.
